import { useCallback, useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import type { AppearanceAssetKind, AppearanceMutationPayload, AppearanceSettings } from '@neta/api-contracts';
import { ChoiceChips, FormSheet, useKeyboardForm } from '@/components/forms';
import { Button, InfoBox, TextField, useToast } from '@/components/ui';
import { deleteAppearanceAsset, getAppearanceSettings, updateAppearanceSettings, uploadAppearanceAsset } from '@/features/settings/api';
import { validateAppearance, validateBrandAsset } from '@/features/settings/form';
import { pickSingleDocument } from '@/features/files/document-picker';
import { toClientError } from '@/lib/api/errors';
import { useSession } from '@/providers/session-provider';
import { useTheme } from '@/providers/theme-provider';
import { spacing, type ColorMode } from '@/theme/tokens';

type Field = 'primaryColor' | 'accentColor'; type RadiusScale = AppearanceMutationPayload['radiusScale'];
const modes: readonly { label: string; value: ColorMode }[] = [{ label: 'Sistem', value: 'system' }, { label: 'Açık', value: 'light' }, { label: 'Koyu', value: 'dark' }];
const radii: readonly { label: string; value: RadiusScale }[] = [{ label: 'Kompakt', value: 'compact' }, { label: 'Standart', value: 'default' }, { label: 'Yumuşak', value: 'soft' }];
const empty: AppearanceSettings = { accentColor: null, darkLogoUrl: null, defaultColorMode: 'system', faviconUrl: null, lightLogoUrl: null, primaryColor: null, radiusScale: 'default' };

export default function AppearanceSettingsFormRoute() {
  const session = useSession(); const { colors } = useTheme(); const { showToast } = useToast(); const keyboard = useKeyboardForm<Field>();
  const [form, setForm] = useState(empty); const [baseline, setBaseline] = useState(JSON.stringify(empty)); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [saved, setSaved] = useState(false);
  useEffect(() => { if (saved) router.back(); }, [saved]);
  const load = useCallback(async () => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const result = await getAppearanceSettings(session.instance, session.user); setForm(result.data); setBaseline(JSON.stringify(result.data)); }, [session]);
  useEffect(() => { let active = true; const id = setTimeout(() => { void load().catch((value) => active && setError(toClientError(value, 'Görünüm ayarları alınamadı.').message)).finally(() => active && setLoading(false)); }, 0); return () => { active = false; clearTimeout(id); }; }, [load]);
  const submit = async () => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const validation = validateAppearance(form.primaryColor, form.accentColor, form.radiusScale); if (validation) { setError(validation); keyboard.focusFirstError({ primaryColor: true }, ['primaryColor', 'accentColor']); return; } const payload: AppearanceMutationPayload = { accentColor: form.accentColor?.trim() || null, defaultColorMode: form.defaultColorMode, primaryColor: form.primaryColor?.trim() || null, radiusScale: form.radiusScale }; setLoading(true); setError(null); try { const result = await updateAppearanceSettings(session.instance, session.user, payload); setForm(result.data); setSaved(true); showToast({ message: 'Görünüm ayarları güncellendi.', tone: 'success' }); } catch (value) { setError(toClientError(value, 'Görünüm ayarları kaydedilemedi.').message); } finally { setLoading(false); } };
  const upload = async (kind: AppearanceAssetKind) => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const file = await pickSingleDocument(['image/png', 'image/jpeg', 'image/webp']); if (!file) return; const validation = validateBrandAsset(file.mimeType, file.size); if (validation) { setError(validation); return; } setLoading(true); setError(null); try { await uploadAppearanceAsset(session.instance, session.user, kind, file.uri); await load(); showToast({ message: 'Marka görseli yüklendi.', tone: 'success' }); } catch (value) { setError(toClientError(value, 'Görsel yüklenemedi.').message); } finally { setLoading(false); } };
  const remove = (kind: AppearanceAssetKind) => Alert.alert('Görsel kaldırılsın mı?', 'Bu işlem marka görünümünü etkiler.', [{ style: 'cancel', text: 'Vazgeç' }, { style: 'destructive', text: 'Kaldır', onPress: () => void performRemove(kind) }]);
  const performRemove = async (kind: AppearanceAssetKind) => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; setLoading(true); try { await deleteAppearanceAsset(session.instance, session.user, kind); await load(); showToast({ message: 'Marka görseli kaldırıldı.', tone: 'success' }); } catch (value) { setError(toClientError(value, 'Görsel kaldırılamadı.').message); } finally { setLoading(false); } };
  return <FormSheet dirty={!saved && JSON.stringify(form) !== baseline} onSubmit={() => void submit()} contentRef={keyboard.contentRef} onViewportLayout={keyboard.onViewportLayout} scrollRef={keyboard.scrollRef} submitting={loading} title="Görünüm ve marka">{error ? <InfoBox description={error} title="İşlem yapılamadı" tone="danger" /> : null}<TextField autoCapitalize="characters" label="Ana renk (#RRGGBB)" onChangeText={(primaryColor) => setForm((value) => ({ ...value, primaryColor }))} onFocus={() => keyboard.onFocus('primaryColor')} ref={keyboard.register('primaryColor')} value={form.primaryColor ?? ''} /><TextField autoCapitalize="characters" label="Vurgu rengi (#RRGGBB)" onChangeText={(accentColor) => setForm((value) => ({ ...value, accentColor }))} onFocus={() => keyboard.onFocus('accentColor')} ref={keyboard.register('accentColor')} value={form.accentColor ?? ''} /><ChoiceChips label="Varsayılan tema" onSelect={(defaultColorMode) => setForm((value) => ({ ...value, defaultColorMode }))} options={modes} selected={form.defaultColorMode} /><ChoiceChips label="Köşe stili" onSelect={(radiusScale) => setForm((value) => ({ ...value, radiusScale }))} options={radii} selected={form.radiusScale} /><Text accessibilityRole="header" style={[styles.heading, { color: colors.text }]}>Marka görselleri</Text><AssetRow exists={Boolean(form.lightLogoUrl)} label="Açık tema logosu" onRemove={() => remove('lightLogo')} onUpload={() => void upload('lightLogo')} /><AssetRow exists={Boolean(form.darkLogoUrl)} label="Koyu tema logosu" onRemove={() => remove('darkLogo')} onUpload={() => void upload('darkLogo')} /><AssetRow exists={Boolean(form.faviconUrl)} label="Favicon" onRemove={() => remove('favicon')} onUpload={() => void upload('favicon')} /></FormSheet>;
}

function AssetRow({ exists, label, onRemove, onUpload }: { exists: boolean; label: string; onRemove: () => void; onUpload: () => void }) { const { colors } = useTheme(); return <View style={styles.asset}><View style={styles.assetCopy}><Text style={[styles.assetTitle, { color: colors.text }]}>{label}</Text><Text style={{ color: colors.textMuted }}>{exists ? 'Yüklendi' : 'Henüz yüklenmedi'}</Text></View><Button onPress={onUpload} variant="secondary">{exists ? 'Değiştir' : 'Yükle'}</Button>{exists ? <Button onPress={onRemove} variant="ghost">Kaldır</Button> : null}</View>; }
const styles = StyleSheet.create({ asset: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, assetCopy: { flex: 1, minWidth: 140 }, assetTitle: { fontSize: 16, fontWeight: '800' }, heading: { fontSize: 19, fontWeight: '900', marginTop: spacing.sm } });
