import { useEffect, useMemo, useState } from 'react';
import { StyleSheet, Text } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';

import type { ClientListItem, ProjectDetail, ProjectStatus, ProjectType } from '@neta/api-contracts';

import { ChoiceChips, FormSheet, NativeDateField, RelationPickerField, useKeyboardForm } from '@/components/forms';
import { InfoBox, TextField, useToast } from '@/components/ui';
import { listAllClients as listClients } from '@/features/clients/api';
import { createProject, getProjectDetail, updateProject } from '@/features/projects/api';
import { buildProjectPayload, type ProjectFormErrors, type ProjectFormState, validateProjectForm } from '@/features/projects/form';
import { toClientError } from '@/lib/api/errors';
import { useSession } from '@/providers/session-provider';
import { useTheme } from '@/providers/theme-provider';

type Field = 'title' | 'description';
const types: readonly { label: string; value: ProjectType }[] = [{ label: 'Müşteri projesi', value: 'client_project' }, { label: 'Yan proje', value: 'side_project' }];
const statuses: readonly { label: string; value: ProjectStatus }[] = [{ label: 'Planlama', value: 'planning' }, { label: 'Aktif', value: 'active' }, { label: 'Duraklatıldı', value: 'paused' }, { label: 'Tamamlandı', value: 'completed' }, { label: 'İptal', value: 'cancelled' }];

export default function ProjectFormRoute() {
  const { projectId } = useLocalSearchParams<{ projectId?: string }>(); const session = useSession(); const { colors } = useTheme(); const { showToast } = useToast(); const keyboard = useKeyboardForm<Field>();
  const empty = useMemo<ProjectFormState>(() => ({ clientId: '', description: '', dueDate: '', sourceLocale: session.instance?.defaultLocale ?? 'tr', status: 'planning', title: '', type: 'client_project' }), [session.instance?.defaultLocale]);
  const [form, setForm] = useState(empty); const [version, setVersion] = useState<string | null>(null); const [baseline, setBaseline] = useState(JSON.stringify(empty)); const [clients, setClients] = useState<ClientListItem[]>([]); const [errors, setErrors] = useState<ProjectFormErrors>({}); const [loading, setLoading] = useState(true); const [submitting, setSubmitting] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (saved) router.back(); }, [saved]);
  useEffect(() => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; let active = true; void Promise.all([listClients(session.instance, session.user, {}), projectId ? getProjectDetail(session.instance, session.user, projectId) : Promise.resolve(null)]).then(([clientPage, detail]) => { if (!active) return; setClients(clientPage.data.items); if (detail) { const next = fromDetail(detail.data, empty.sourceLocale); setForm(next); setVersion(detail.data.updatedAt); setBaseline(JSON.stringify(next)); } }).catch((loadError) => active && setError(toClientError(loadError, 'Proje formu yüklenemedi.').message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [empty.sourceLocale, projectId, session]);
  const submit = async () => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const nextErrors = validateProjectForm(form); setErrors(nextErrors); if (Object.keys(nextErrors).length) { keyboard.focusFirstError(nextErrors, ['title']); return; } setSubmitting(true); setError(null); try { const payload = { ...buildProjectPayload(form), ...(projectId ? { version } : {}) }; const result = projectId ? await updateProject(session.instance, session.user, projectId, payload) : await createProject(session.instance, session.user, payload); setSaved(true); showToast({ message: 'Proje bilgileri ve ilişkileri güncellendi.', title: result.data.title, tone: 'success' }); } catch (submitError) { setError(toClientError(submitError, 'Proje kaydedilemedi.').message); } finally { setSubmitting(false); } };
  return <FormSheet dirty={!saved && !loading && JSON.stringify(form) !== baseline} onSubmit={() => void submit()} scrollRef={keyboard.scrollRef} submitLabel={projectId ? 'Değişiklikleri kaydet' : 'Projeyi oluştur'} submitting={submitting || loading} title={projectId ? 'Projeyi düzenle' : 'Yeni proje'}><Text style={[styles.lead, { color: colors.textMuted }]}>Proje türünü ve ilişkili müşteriyi seç. Ham kayıt kimliği girmen gerekmez.</Text>{error ? <InfoBox description={error} title="Form kullanılamıyor" tone="danger" /> : null}<ChoiceChips label="Proje türü" onSelect={(type) => setForm((value) => ({ ...value, clientId: type === 'side_project' ? '' : value.clientId, type }))} options={types} selected={form.type} />{form.type === 'client_project' ? <RelationPickerField label="Müşteri" onChange={(clientId) => setForm((value) => ({ ...value, clientId: clientId ?? '' }))} options={clients.map((client) => ({ description: client.email ?? undefined, id: client.id, label: client.displayName }))} value={form.clientId || null} /> : null}<TextField error={errors.title} label={`Proje adı (${form.sourceLocale})`} onChangeText={(title) => { setForm((value) => ({ ...value, title })); setErrors((value) => ({ ...value, title: undefined })); }} onFocus={() => keyboard.onFocus('title')} ref={keyboard.register('title')} value={form.title} /><TextField label="Açıklama" multiline onChangeText={(description) => setForm((value) => ({ ...value, description }))} onFocus={() => keyboard.onFocus('description')} ref={keyboard.register('description')} textAlignVertical="top" value={form.description} /><ChoiceChips label="Durum" onSelect={(status) => setForm((value) => ({ ...value, status }))} options={statuses} selected={form.status ?? 'planning'} /><NativeDateField label="Bitiş tarihi" onChange={(date) => { setForm((value) => ({ ...value, dueDate: date ? dateOnly(date) : '' })); setErrors((value) => ({ ...value, dueDate: undefined })); }} value={form.dueDate ? new Date(`${form.dueDate}T12:00:00`) : null} />{errors.dueDate ? <InfoBox description={errors.dueDate} tone="danger" /> : null}</FormSheet>;
}
function fromDetail(value: ProjectDetail, locale: string): ProjectFormState { return { clientId: value.clientId ?? '', description: value.translations[locale]?.description ?? '', dueDate: value.dueDate ?? '', sourceLocale: locale, status: value.status, title: value.translations[locale]?.name ?? value.title, type: value.type }; }
function dateOnly(date: Date) { const year = date.getFullYear(); const month = String(date.getMonth() + 1).padStart(2, '0'); const day = String(date.getDate()).padStart(2, '0'); return `${year}-${month}-${day}`; }
const styles = StyleSheet.create({ lead: { fontSize: 15, lineHeight: 22 } });
