import { useCallback, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { type Href, router, useFocusEffect, useLocalSearchParams } from 'expo-router';

import type { TaskDetail, TaskStatus } from '@neta/api-contracts';

import { Badge, Button, Card, EmptyState, InfoBox, ListRow, Screen, Skeleton, useToast } from '@/components/ui';
import { deleteTask, getTaskDetail, updateTaskStatus } from '@/features/tasks/api';
import { toClientError } from '@/lib/api/errors';
import { formatDateTime } from '@/lib/resource/format';
import { useSession } from '@/providers/session-provider';
import { useTheme } from '@/providers/theme-provider';
import { spacing } from '@/theme/tokens';

const statusActions: readonly { label: string; value: TaskStatus }[] = [{ label: 'Yapılacak', value: 'todo' }, { label: 'Devam ediyor', value: 'in_progress' }, { label: 'Tamamlandı', value: 'done' }];

export default function TaskDetailRoute() {
  const { id } = useLocalSearchParams<{ id: string }>(); const session = useSession(); const { colors } = useTheme(); const { showToast } = useToast(); const [task, setTask] = useState<TaskDetail | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [pendingStatus, setPendingStatus] = useState<TaskStatus | null>(null);
  const load = useCallback(async () => { if (!id || session.status !== 'authenticated' || session.role !== 'freelancer') return; setLoading(true); setError(null); try { setTask((await getTaskDetail(session.instance, session.user, id)).data); } catch (loadError) { setError(toClientError(loadError, 'Görev detayı alınamadı.').message); } finally { setLoading(false); } }, [id, session]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const changeStatus = async (status: TaskStatus) => { if (!task || session.status !== 'authenticated' || session.role !== 'freelancer' || pendingStatus) return; const previous = task; setPendingStatus(status); setTask({ ...task, status }); try { const result = await updateTaskStatus(session.instance, session.user, task.id, { status, version: task.version }); setTask(result.data); showToast({ message: `${statusLabel(status)} olarak güncellendi.`, title: task.title, tone: 'success' }); } catch (statusError) { setTask(previous); showToast({ message: toClientError(statusError, 'Durum güncellenemedi.').message, title: 'Değişiklik geri alındı', tone: 'danger' }); } finally { setPendingStatus(null); } };
  const confirmDelete = () => Alert.alert('Görev silinsin mi?', 'Bu işlem geri alınamaz.', [{ style: 'cancel', text: 'Vazgeç' }, { style: 'destructive', text: 'Sil', onPress: () => void runDelete() }]);
  const runDelete = async () => { if (!task || !task.version || session.status !== 'authenticated' || session.role !== 'freelancer') return; try { await deleteTask(session.instance, session.user, task.id, task.version); showToast({ message: 'Görev kalıcı olarak silindi.', title: task.title, tone: 'success' }); router.back(); } catch (deleteError) { showToast({ message: toClientError(deleteError, 'Görev silinemedi.').message, title: 'Silme başarısız', tone: 'danger' }); } };
  if (loading && !task) return <Screen scroll><View style={styles.content}><Skeleton height={150} /><Skeleton height={220} /></View></Screen>;
  if (error && !task) return <Screen centered contentStyle={styles.centered}><InfoBox action={<Button onPress={() => void load()}>Tekrar dene</Button>} description={error} title="Görev açılamadı" tone="danger" /></Screen>;
  if (!task) return <Screen centered><EmptyState description="Görev kaydı bulunamadı." title="Görev yok" /></Screen>;
  const locale = session.instance?.defaultLocale ?? 'tr';
  return <Screen onRefresh={() => void load()} refreshing={loading} scroll><View style={styles.content}>{error ? <InfoBox description={error} title="Görev yenilenemedi" tone="warning" /> : null}<Card style={styles.hero}><View style={styles.row}><View style={styles.copy}><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>{task.title}</Text><Text style={[styles.description, { color: colors.textMuted }]}>{task.projectName ?? 'Projesiz görev'} · {task.clientName ?? 'Müşteri yok'}</Text></View><Badge tone={task.status === 'done' ? 'success' : task.priority === 'urgent' ? 'danger' : 'primary'}>{statusLabel(task.status)}</Badge></View><View style={styles.actions}><Button onPress={() => router.push({ pathname: '/task', params: { taskId: id } } as unknown as Href)} variant="secondary">Düzenle</Button><Button onPress={confirmDelete} variant="ghost">Sil</Button></View></Card><Card><ListRow description={priorityLabel(task.priority)} icon={{ ios: 'flag.fill', android: 'flag' }} title="Öncelik" /><ListRow description={task.dueAt ? formatDateTime(task.dueAt, locale) : 'Belirlenmedi'} icon={{ ios: 'calendar', android: 'calendar_month' }} title="Son tarih" /><ListRow description={task.estimatedMinutes ? `${task.estimatedMinutes} dakika` : 'Belirlenmedi'} icon={{ ios: 'clock.fill', android: 'schedule' }} title="Tahmini süre" /><ListRow description={task.isPublicToClient ? 'Müşteri portalında görünür' : 'Yalnızca sana görünür'} icon={{ ios: task.isPublicToClient ? 'eye.fill' : 'eye.slash.fill', android: task.isPublicToClient ? 'visibility' : 'visibility_off' }} title="Görünürlük" /></Card><View style={styles.section}><Text accessibilityRole="header" style={[styles.sectionTitle, { color: colors.text }]}>Durumu güncelle</Text><View accessibilityLabel="Görev durumu" accessibilityRole="radiogroup" style={styles.actions}>{statusActions.map((item) => <Button accessibilityRole="radio" accessibilityState={{ checked: task.status === item.value }} key={item.value} loading={pendingStatus === item.value} onPress={() => void changeStatus(item.value)} variant={task.status === item.value ? 'primary' : 'secondary'}>{item.label}</Button>)}</View></View></View></Screen>;
}
function statusLabel(value: TaskStatus) { return { cancelled: 'İptal', done: 'Tamamlandı', in_progress: 'Devam ediyor', todo: 'Yapılacak' }[value]; }
function priorityLabel(value: TaskDetail['priority']) { return { high: 'Yüksek', low: 'Düşük', medium: 'Orta', urgent: 'Acil' }[value]; }
const styles = StyleSheet.create({ actions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, centered: { maxWidth: 560, padding: spacing.lg }, content: { gap: spacing.md, paddingVertical: spacing.xl }, copy: { flex: 1, gap: spacing.xs }, description: { fontSize: 14, lineHeight: 21 }, hero: { gap: spacing.lg }, row: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.md }, section: { gap: spacing.sm }, sectionTitle: { fontSize: 20, fontWeight: '900' }, title: { fontSize: 28, fontWeight: '900', letterSpacing: -0.5 } });
