import { useCallback, useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { type Href, router, useFocusEffect } from 'expo-router';

import type { PaginatedResponse, ProjectListItem, ProjectStatus } from '@neta/api-contracts';

import { AppIcon, Badge, Button, Card, EmptyState, InfoBox, Screen, Skeleton, TextField } from '@/components/ui';
import { listProjects, type ProjectListFilters } from '@/features/projects/api';
import { appendResourcePage } from '@/lib/resource/pagination';
import { toClientError } from '@/lib/api/errors';
import { formatDateTime } from '@/lib/resource/format';
import { hasInstanceCapability } from '@/lib/instance/capabilities';
import { useSession } from '@/providers/session-provider';
import { useTheme } from '@/providers/theme-provider';
import { radius, spacing } from '@/theme/tokens';

const statuses: readonly { label: string; value: ProjectStatus | undefined }[] = [{ label: 'Tümü', value: undefined }, { label: 'Planlama', value: 'planning' }, { label: 'Aktif', value: 'active' }, { label: 'Duraklatıldı', value: 'paused' }, { label: 'Tamamlandı', value: 'completed' }];

export default function ProjectsScreen() {
  const { colors } = useTheme(); const session = useSession(); const [search, setSearch] = useState(''); const [query, setQuery] = useState(''); const [status, setStatus] = useState<ProjectStatus | undefined>(); const [page, setPage] = useState<PaginatedResponse<ProjectListItem> | null>(null); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false); const requestRef = useRef(0);
  const load = useCallback(async (cursor?: string) => { if (session.status !== 'authenticated' || session.role !== 'freelancer') return; const requestId = ++requestRef.current; setLoading(true); setError(null); try { const filters: ProjectListFilters = {}; if (cursor) filters.cursor = cursor; if (query) filters.search = query; if (status) filters.status = status; const result = await listProjects(session.instance, session.user, filters); if (requestId === requestRef.current) setPage((current) => cursor ? appendResourcePage(current, result.data) : result.data); } catch (loadError) { if (requestId === requestRef.current) setError(toClientError(loadError, 'Projeler alınamadı.').message); } finally { if (requestId === requestRef.current) setLoading(false); } }, [query, session, status]);
  useEffect(() => { const timeout = setTimeout(() => setQuery(search.trim()), 300); return () => clearTimeout(timeout); }, [search]);
  useFocusEffect(useCallback(() => { void load(); return () => { requestRef.current += 1; }; }, [load]));
  const canMutate = session.instance ? hasInstanceCapability(session.instance, 'freelancer.core-mutations.v1') : false;
  return <Screen onRefresh={() => void load()} refreshing={loading && page !== null} scroll><View style={styles.content}><View style={styles.heading}><View style={styles.copy}><Badge tone="primary">Projeler</Badge><Text accessibilityRole="header" style={[styles.title, { color: colors.text }]}>Proje merkezi</Text><Text style={[styles.description, { color: colors.textMuted }]}>Plan, görev, revizyon ve dosyaları proje bağlamında takip et.</Text></View>{canMutate ? <Button onPress={() => router.push('/project' as Href)}>Yeni proje</Button> : null}</View><Card style={styles.filters}><TextField clearButtonMode="while-editing" label="Projelerde ara" onChangeText={setSearch} placeholder="Proje adı" returnKeyType="search" value={search} /><View accessibilityLabel="Proje durumu" accessibilityRole="radiogroup" style={styles.chips}>{statuses.map((item) => <Chip key={item.label} label={item.label} onPress={() => setStatus(item.value)} selected={item.value === status} />)}</View></Card>{error ? <InfoBox action={<Button onPress={() => void load()} variant="ghost">Tekrar dene</Button>} description={error} title="Projeler yüklenemedi" tone="danger" /> : null}{loading && !page ? <><ProjectSkeleton /><ProjectSkeleton /></> : null}{!loading && page?.items.length === 0 ? <EmptyState action={canMutate ? <Button onPress={() => router.push('/project' as Href)}>İlk projeyi oluştur</Button> : undefined} description="Aramayı değiştir veya yeni bir proje başlat." title="Proje bulunamadı" /> : null}<View style={styles.list}>{page?.items.map((project) => <ProjectCard key={project.id} locale={session.instance?.defaultLocale ?? 'tr'} project={project} />)}</View>{page?.pageInfo.hasNextPage && page.pageInfo.nextCursor ? <Button loading={loading} onPress={() => void load(page.pageInfo.nextCursor ?? undefined)} variant="secondary">Daha fazla yükle</Button> : null}</View></Screen>;
}
function ProjectCard({ locale, project }: { locale: string; project: ProjectListItem }) { const { colors } = useTheme(); return <Pressable accessibilityHint="Proje detayını açar" accessibilityLabel={`${project.title}, yüzde ${project.progress}`} accessibilityRole="button" onPress={() => router.push({ pathname: '/(owner)/projects/[id]', params: { id: project.id } } as unknown as Href)} style={({ pressed }) => pressed && { opacity: 0.8 }}><Card style={styles.project}><View style={styles.projectTop}><View style={[styles.icon, { backgroundColor: colors.primary }]}><AppIcon color={colors.primaryForeground} name={{ ios: 'folder.fill', android: 'folder' }} /></View><View style={styles.copy}><View style={styles.row}><Text numberOfLines={1} style={[styles.itemTitle, { color: colors.text }]}>{project.title}</Text><Badge tone={project.status === 'completed' ? 'success' : project.status === 'paused' ? 'warning' : 'primary'}>{projectStatus(project.status)}</Badge></View><Text style={[styles.description, { color: colors.textMuted }]}>{project.clientName ?? 'Kişisel proje'} · {project.type === 'side_project' ? 'Yan proje' : 'Müşteri projesi'}</Text></View><AppIcon color={colors.textSubtle} name={{ ios: 'chevron.right', android: 'chevron_right' }} size={18} /></View><View accessibilityLabel={`İlerleme yüzde ${project.progress}`} accessibilityRole="progressbar" accessibilityValue={{ max: 100, min: 0, now: project.progress }} style={[styles.track, { backgroundColor: colors.surfaceMuted }]}><View style={[styles.progress, { backgroundColor: colors.primary, width: `${project.progress}%` }]} /></View><Text style={[styles.caption, { color: colors.textSubtle }]}>%{project.progress} · {project.dueDate ? `Bitiş ${project.dueDate}` : 'Bitiş tarihi yok'} · {formatDateTime(project.updatedAt, locale)}</Text></Card></Pressable>; }
function Chip({ label, onPress, selected }: { label: string; onPress: () => void; selected: boolean }) { const { colors } = useTheme(); return <Pressable accessibilityRole="radio" accessibilityState={{ checked: selected }} onPress={onPress} style={[styles.chip, { backgroundColor: selected ? colors.primary : colors.surfaceMuted, borderColor: colors.border }]}><Text style={{ color: selected ? colors.primaryForeground : colors.text }}>{label}</Text></Pressable>; }
function ProjectSkeleton() { return <Card style={styles.project}><Skeleton height={22} width="55%" /><Skeleton height={14} /><Skeleton height={8} /></Card>; }
function projectStatus(value: ProjectStatus) { return { active: 'Aktif', cancelled: 'İptal', completed: 'Tamamlandı', paused: 'Duraklatıldı', planning: 'Planlama' }[value]; }
const styles = StyleSheet.create({ caption: { fontSize: 12, lineHeight: 17 }, chip: { borderRadius: radius.pill, borderWidth: StyleSheet.hairlineWidth, justifyContent: 'center', minHeight: 48, paddingHorizontal: spacing.md }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, content: { gap: spacing.md, paddingVertical: spacing.xl }, copy: { flex: 1, gap: spacing.xs }, description: { fontSize: 14, lineHeight: 20 }, filters: { gap: spacing.md }, heading: { alignItems: 'flex-end', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md, justifyContent: 'space-between' }, icon: { alignItems: 'center', borderRadius: radius.lg, height: 48, justifyContent: 'center', width: 48 }, itemTitle: { flex: 1, fontSize: 17, fontWeight: '800' }, list: { gap: spacing.sm }, progress: { borderRadius: radius.pill, height: '100%' }, project: { gap: spacing.md }, projectTop: { alignItems: 'center', flexDirection: 'row', gap: spacing.md }, row: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm }, title: { fontSize: 30, fontWeight: '900', letterSpacing: -0.6 }, track: { borderRadius: radius.pill, height: 8, overflow: 'hidden' } });
